### ISSUE TITLE
Is this repo will realease in future?

### ISSUE THREAD

**Issue by AleksandrRadik** [availproject/txwrapper#2]
Hi there! Thank's for publish this instrument's for implement functionality for generate transaction offline, we wanna use it's in our wallet but I see that's this one don't realesed yet. So for now I just clone this repo in out project and use, but maybe in future I can install this with npm and got all updates in future?

**Comment by Leouarz** [comment]
Hello, sorry for the late response. The repo is published in npm right now : https://www.npmjs.com/package/avail-txwrapper
